version: '3'

services:
  pokemon_server:
    build:
      context: .
      dockerfile: container_server/pokemon_server.Dockerfile
    ports:
      - "50051:50051"
  pokemon_client:
    build:
      context: .
      dockerfile: container_client/pokemon_client.Dockerfile
    depends_on:
      - "pokemon_server"
    command: ["./wait-for-it.sh", "pokemon_server:50051", "--", "python", "pokemon_client.py"]
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  pokemon_website:
    build:
      context: .
      dockerfile: container_website/pokemon_website.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - "redis"