version: '3'

services:
  pokemon-server:
    build:
      context: .
      dockerfile: container-server/pokemon-server.Dockerfile
    ports:
      - "50051:50051"
  pokemon-client:
    build:
      context: .
      dockerfile: container-client/pokemon-client.Dockerfile
    depends_on:
      - "pokemon-server"
    command: ["./wait-for-it.sh", "pokemon-server:50051", "--", "python", "pokemon-client.py"]
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  pokemon-website:
    build:
      context: .
      dockerfile: container-website/pokemon-website.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - "redis"