# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PokemonServer_pb2 as PokemonServer__pb2


class PokeDataStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestPokemon = channel.unary_stream(
                '/PokeData/RequestPokemon',
                request_serializer=PokemonServer__pb2.PokeRequest.SerializeToString,
                response_deserializer=PokemonServer__pb2.PokeResponse.FromString,
                )


class PokeDataServicer(object):
    """The greeting service definition.
    """

    def RequestPokemon(self, request, context):
        """Sends data from the file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokeDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestPokemon': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestPokemon,
                    request_deserializer=PokemonServer__pb2.PokeRequest.FromString,
                    response_serializer=PokemonServer__pb2.PokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PokeData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PokeData(object):
    """The greeting service definition.
    """

    @staticmethod
    def RequestPokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PokeData/RequestPokemon',
            PokemonServer__pb2.PokeRequest.SerializeToString,
            PokemonServer__pb2.PokeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
