apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimon-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digimon-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: digimon-client
    spec:
      containers:
      - name: digimon-client
        image: eoghanspillane/digimon-client:newest
