apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokemon-server
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pokemon-server
    spec:
      containers:
      - name: pokemon-server
        image: eoghanspillane/pokemon-server:newest
        ports:
        - containerPort: 50051