apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-website-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pokemon-website
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pokemon-website
    spec:
      containers:
      - name: pokemon-website
        image: eoghanspillane/pokemonwebsite:latest
        ports:
        - containerPort: 5000
